### ISSUE TITLE
Problem with axes in cake mode

### ISSUE THREAD

**Issue by erangre** [Dioptas/Dioptas#104]
Something happened to the axes in cake mode.
The azimuth range is showing up wrong sometimes.
When zooming the axes don't update to the new range.

**Comment by CPrescher** [comment]
Since when does this occur? Just recently or already some time before?

**Comment by erangre** [comment]
I am not sure. Someone else noticed it and notified me, so I checked it yesterday and saw it.
I think also the line is not appearing on cake.
A few months ago it was working fine because I remember I tried to get the x scale to match on cake and pattern and couldn't get it to work, but for the cake separately it was fine.
