### ISSUE TITLE
Mac release doesn't install

### ISSUE THREAD

**Issue by aniryel** [Dioptas/Dioptas#108]
I was trying to install the release for Mac, but after pressing "Open" nothing happens, the process disappears. Could you please help me out?

**Comment by CPrescher** [comment]
Hi, 
could you please give me more information:

1. how did you install? (The executable, anaconda, ...?)
2. What OS X version are you using?
3. Did you try: FAQ number 3 in http://www.clemensprescher.com/programs/dioptas/dioptas-faq ?

**Comment by aniryel** [comment]
Hi,

I have macOS Sierra, version 10.12.6, I was trying to install the executive for Mac you have on the Github with the last update.
I didn't try the FAQ number 3 as it doesn't give me any error. It just disappears from processes and nothing happens at all after I try to open the installation.
