### ISSUE TITLE
Cannot open Dioptas 0.5.1 executable

### ISSUE THREAD

**Issue by lgpmartins** [Dioptas/Dioptas#116]
Hi,

I have been trying to install the Dioptas 0.5.1 executable version for Windows 64 and it does not work. No error message shows up. Once I cick to open the Dioptas executable, nothing happens.

There was no problem when opening the executables of Dioptas 0.5.0 and 0.041. 

Could you help me with this?

**Comment by CPrescher** [comment]
I just tried out whether Dioptas 0.5.1 runs on a new computer with a brand new windows installation and no libraries installed. It works without any issues. The only thing I need to do is to right click the Dioptas.exe and disable the security check under properties.

**Comment by anyaL1966** [comment]
Hello, my system is Windows10, when trying to start Dioptas_Win64_0.4.1., error message appears: Error loading Python DLL: ...\python35.dll (error code 126). But this file (python35.dll) is contained in the program folder!  thanks for your help
![ErrorDioptas](https://user-images.githubusercontent.com/66294475/83484564-694c1200-a4cf-11ea-9604-94aaf00d54b1.jpg)

**Comment by CPrescher** [comment]
Hi,

please try extracting the zip to a folder first, and then run the Dioptas.exe file. Please also use the latest Version of Dioptas from: https://github.com/Dioptas/Dioptas/releases

Best wishes,
Clemens
