### ISSUE TITLE
PyInstaller is missing several binary extentions

### ISSUE THREAD

**Issue by kif** [Dioptas/Dioptas#130]
At least under windows, the binary extension of pyFAI are not shipped.
see: https://github.com/karnevskiy/Dioptas/blob/feat/scan_processing/.github/workflows/build_windows.yml

I would suggest to dynamically define the hidden import for pyFAI and fabio based on the inspection of sys.module in Dioptas.spec

**Comment by CPrescher** [comment]
Hi Jerome,

how would I notice, that it is not shipped within the pyinstaller executable?
