### ISSUE TITLE
Loading Phases Out 

### ISSUE THREAD

**Issue by jlgonzal12** [Dioptas/Dioptas#138]
When loading cif files into Dioptas to compare phases they do not load. 
![Dioptas error](https://user-images.githubusercontent.com/119887472/205712247-f76e3dea-35b4-408c-9f28-101b3b56ffbc.jpg)

**Comment by CPrescher** [comment]
Hi,

there could be several reasons for this. What CIF file are you loading? Is it a "good" cif file? Where did you get it from? Can you check it under https://checkcif.iucr.org/ ?

Please also use the latest Dioptas version which is 0.5.5. you can download it from https://github.com/Dioptas/Dioptas/releases/tag/0.5.5

0.5.0 is from 2019 and I can for example see, that there was an bugfix related to the space group number for version 0.5.1:

loading cif files with the newer '_space_group_IT_number' representation work now correctly

Best wishes,
Clemens

**Comment by CPrescher** [comment]
I will close this due to inactivity
