### ISSUE TITLE
Type Error: mouse position in cake view

### ISSUE THREAD

**Issue by CPHalbert** [Dioptas/Dioptas#147]
When viewing a file in cake view, an error occurs when the mouse is positioned at y=0.

<class 'TypeError'>: 
must be real number, not NoneType
--------------------------------------------------------------------------------
  File "dioptas\controller\integration\ImageController.py", line 773, in show_img_mouse_position
--------------------------------------------------------------------------------
Dioptas Version: 0.5.7

**Comment by CPrescher** [comment]
Thanks, should will be fixed in next release.
