### ISSUE TITLE
Calibration Auto Increase disabling doesn't do anything

### ISSUE THREAD

**Issue by erangre** [Dioptas/Dioptas#148]
Dioptas 0.5.7 on Linux
disabling the autoincrease for peak search does not work (in both single peak and automatic peak search modes).
The ring number still increases by 1 after each click.

**Comment by lbarmore** [comment]
I'm having the same issue with version 0.5.7 on Windows. After unchecking the "automatic increase" box, the ring number still increases automatically with every peak selected.
