### ISSUE TITLE
Cannot run dioptas if installed by another user

### ISSUE THREAD

**Issue by t20100** [Dioptas/Dioptas#185]
With current tip of the project,under Linux,  it is not possible to run dioptas with a different user than the one who installed it. 
This is due to `apply_stylesheet` writing a file into the installed path:

https://github.com/Dioptas/Dioptas/blob/11fba8d9f54ea919ea1bb94eefe39a552f34eadf/dioptas/__init__.py#L45-L56

Passing `save_as` doesn't seems to be needed and would solve the issue

**Comment by CPrescher** [comment]
I have saved it temporarily to better understand how to tweak the custom styling.
You are right this is unnecessary.
