### ISSUE TITLE
Error when saving pattern

### ISSUE THREAD

**Issue by rhyzp** [Dioptas/Dioptas#197]
Hello,

I'm using 0.6.0 release of dioptas. I'm receiving the following error.

Error information:
--------------------------------------------------------------------------------
2024-05-08, 15:45:45
--------------------------------------------------------------------------------
<class 'AttributeError'>: 
'Pattern' object has no attribute 'has_background'
--------------------------------------------------------------------------------
  File "dioptas\controller\integration\ImageController.py", line 493, in load_next_img
  File "dioptas\model\ImgModel.py", line 465, in load_next_file
  File "dioptas\model\ImgModel.py", line 151, in load
  File "dioptas\model\util\signal.py", line 65, in emit
  File "dioptas\model\util\signal.py", line 75, in _serve_listeners
  File "dioptas\model\Configuration.py", line 123, in integrate_image_1d
  File "dioptas\model\Configuration.py", line 242, in _auto_save_patterns
--------------------------------------------------------------------------------
Dioptas Version: 0.6.0

I loaded the diffraction image and calibration file, created a mask and had a background created using the button on the pattern overlay. I had it set to autoprocess and autocreate in the process tab and set the directory which I wanted the processed patterns saved to. Unfortunately when I click next file this message pops up and while the pattern file does save it does not save with the subtracted background. It's not too much of an issue since when I manually click the save pattern button on the overlay it saves it properly it does get a bit cumbersome when there are a lot of image files to process. 

Thank you for creating and maintaining the software!

**Comment by CPrescher** [comment]
Thank you very much for the detailed bug report! 

It will be fixed in the next version. 

For now, you can batch integrate files (load multiple files in the file-dialog) to save all your files as text files at once.
