### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by CJ-Wright** [Dioptas/Dioptas#41]
Are there any plans for python 3 support?

**Comment by CPrescher** [comment]
Why do you ask?
Dioptas is fully python 3 compatible in the develop branch.

**Comment by CJ-Wright** [comment]
But are you testing against it? The `.travis.yml` file only specifies python 2.7 in the build matrix.

**Comment by CJ-Wright** [comment]
Also your `readme.md` specifies python 2.7 as a requirement.

**Comment by CPrescher** [comment]
yes, because there is always a memory error when the tests are run under python 3 in travis
and till now I could not track it down what is causing this....

**Comment by CPrescher** [comment]
What actually also happens for the python 2.7 testing right now... but i have to look into it again. :)
