### ISSUE TITLE
Dioptas Windows 10 Compatability 

### ISSUE THREAD

**Issue by Diver88** [Dioptas/Dioptas#42]
![uf1vv c5 737y 59nzh4q 8](https://cloud.githubusercontent.com/assets/10702499/26155098/9867cd42-3b44-11e7-8e5d-abc3c5a328b6.png)
Best wishes,
Yang

**Comment by CPrescher** [comment]
Hi yang,

this could be induced by having either Dioptas installed in a file path with chinese characters or the file in a file path with chinese characters.

Could you please check and try to use only non-chinese characters?

Best wishes,
Clemens

**Comment by CPrescher** [comment]
Hi Yang,

did you manage to run Dioptas finally?
If I do not receive an answer in the next day, the issue will be closed.

Best wishes,
Clemens
