### ISSUE TITLE
Need to check if pattern background parameters are saved/loaded in/from .dio

### ISSUE THREAD

**Issue by erangre** [Dioptas/Dioptas#51]
When loading .dio files it seems that the X-range and other parameters for pattern background are not being loaded (or maybe not saved at all before that). Need to test this.

**Comment by CPrescher** [comment]
Thanks for pointing this out.
This was also not working just with different configurations.
The .dio file has everything included (except for the state of the inspection).

It is fixed in 87139228ea4f151fa96c88422814e3203cfa2a27
