### ISSUE TITLE
Correcting .edf file with spline file

### ISSUE THREAD

**Issue by sedmak** [Dioptas/Dioptas#69]
Hi, I'd like to correct the .edf files for a spatial distortion of the detector - .spline file. Is it possible to implement into Dioptas?

**Comment by CPrescher** [comment]
Hi, in principle pyFAI support s spline files for spatial distoratio corrections, therefore it sould be possible to implement. However i have never played with it, do you have experience?

**Comment by sedmak** [comment]
Hi, 
I managed to make it work with pyFAI with a few lines. 

import fabio
import pyFAI
from pyFAI.distortion import Distortion
import os,sys
from pyFAI import detectors

spline_file=('f4mnew.spline')  => spline file for our frelon detector
hd = pyFAI.detectors.FReLoN(splineFile=spline_file)
dis = Distortion(hd)#, resize=True)  => defines type of a distortion 

for i in(glob.glob('*.edf')):    => correct all the files in the current dir with .edf extension
    im=fabio.open(i)
    raw=im.data
    corrected=dis1.correct(raw1) 
    im.data=corrected
    im.write('cor_%s.edf'%i)

Is it possible to implement it somehow into Dioptas then? 
Thanks!

**Comment by CPrescher** [comment]
Hi again,

would it be possible that you can upload a sample image, calibration and spline file, so that i can test that everything works correctly?

Best wishes,
Clemens

**Comment by sedmak** [comment]
Hi, 
So here is an edf image of a CeO2 that we use for calibration and a spline file of the detector. 
Best,
Pavel
[files.zip](https://github.com/Dioptas/Dioptas/files/1915738/files.zip)

**Comment by CPrescher** [comment]
So this is implemented now in the develop branch and will be in the next release, thank you for the test files.
