### ISSUE TITLE
Error while loading file

### ISSUE THREAD

**Issue by baptiste7590** [Dioptas/Dioptas#71]
Hi,

This error message appears when I try to load a file :

![ooops](https://user-images.githubusercontent.com/38859487/39430374-f8d076e2-4c8d-11e8-8185-dc271d1dcafa.png)

What should I do ?

Best wishes,
Baptiste

**Comment by CPrescher** [comment]
Hi,

I do not know.
what file is it? Where do you got the image from, and could you maybe attach a sample image here in the comment?

Best wishes,
Clemens

**Comment by baptiste7590** [comment]
It's a .tif file. 

I first treat a raw image (in .tif) with ImageJ and then when I save it (in .tif) I can't open it anymore with dioptas. However I can open a raw image without any problem.
I know that this treatment process works with Mac but not with Windows.

I can't attach an image here the .tif file is not supported.

**Comment by CPrescher** [comment]
Why do you need to treat it with ImageJ? Is there a specific setting in ImageJ  you are using when saving it?

Could you please upload the original file (before imageJ), the file after treatment with imageJ and tell me what exactly you do with imageJ, so that i can do it myself?

Files can be uploaded packed in a zip file.

Best wishes,
Clemens

**Comment by baptiste7590** [comment]
Hi Clemens,

Sorry for the late answer but I finally find a way to open the file.
After the treatment on ImageJ I just have to export the image instead of saving it under a certain file and I can open it on dioptas without any problem.

Thanks for your time.

Best wishes,
Baptiste

**Comment by CPrescher** [comment]
Ok i am happy that the issue is solved for you. But I still would like to know what ImageJ does, that Dioptas does not like under windows....
