### ISSUE TITLE
Image view changes when opening same image twice

### ISSUE THREAD

**Issue by Treeed** [Dioptas/Dioptas#96]
For some reason when opening an image and opening the same image again the view changes. It most notably gets darker and in the integration view sometimes changes position. This gives the impression of having opened a different image or the image data having changed.
Reproducible with the current develop branch and any image, tested with http://eeweb.poly.edu/~yao/EL5123/image/lena_gray.bmp

**Comment by CPrescher** [comment]
I tested this in the current develop branch version and it seems to be fixed.
